#!/usr/bin/python

import nose
import sys
from nose.plugins.base import Plugin


class ExtensionPlugin(Plugin):
    name = "ExtensionPlugin"

    def options(self, parser, env):
        Plugin.options(self, parser, env)

    def configure(self, options, config):
        Plugin.configure(self, options, config)
        self.enabled = True

    def wantFile(self, file):
        return file.endswith('.py')

    def wantDirectory(self, directory):
        return True

    def wantModule(self, file):
        return True


if __name__ == '__main__':
    includeDirs = ["-w", ".", ".."]
    args = sys.argv
    args.append('--with-coverage')
    args.append('--cover-package=UML')
    args.extend(includeDirs)
    nose.run(addplugins=[ExtensionPlugin()], argv=args)
    sys.stdin = open('/dev/tty')
    blank = raw_input("Press Enter to continue...")
    exit(0)

