#!/usr/bin/python

import nose
import sys
from nose.plugins.base import Plugin
from nose.plugins.cover import Coverage

class ExtensionPlugin(Plugin):

    name = "ExtensionPlugin"

    def options(self, parser, env):
        Plugin.options(self,parser,env)

    def configure(self, options, config):
        Plugin.configure(self, options, config)
        self.enabled = True

    def wantFile(self, file):
        return file.endswith('.py')

    def wantDirectory(self,directory):
        return True

    def wantModule(self,file):
        return True


if __name__ == '__main__':
    includeDirs = ["-w", ".", ".."]
    nose.run(addplugins=[ExtensionPlugin(), Coverage()], argv=sys.argv.extend(includeDirs))
    exit(0)
