#!/usr/bin/python

import nose
import re
from nose.plugins.base import Plugin
from nose.plugins.cover import Coverage

class ExtensionPlugin(Plugin):

    name = "ExtensionPlugin"

    def options(self, parser, env):
        Plugin.options(self,parser,env)

    def configure(self, options, config):
        Plugin.configure(self, options, config)
        self.enabled = True

    def wantFile(self, file):
        return file.endswith('.py')

    def wantDirectory(self,directory):
        return True

    def wantModule(self,file):
        return True


if __name__ == '__main__':
    includeDirs = ["-w", ".", ".."]
    result = nose.run(addplugins=[ExtensionPlugin(), Coverage()], argv=sys.argv.extend(includeDirs))
    if not result:
    	override = raw_input('Some tests have failed.  Do you want to push your changes anyway (y/n)?').lower()

    while True:
    	if re.match('y(es)?', override):
    		exit(0)
    	elif re.match('n(o)?', override):
    		exit(1)
    	else:
    		override = raw_input('y/n:').lower()

